#!/bin/sh

### This script will erase the existing ~/.hammerspoon directory and 
### copy in the contents of the src/ directory, thus updating it with the latest code.

if [ ! -d "$HOME/.hammerspoon/" ]; then
  echo "Please install Hammerspoon: http://www.hammerspoon.org/"
	exit 1
fi

rm -Rf "$HOME/.hammerspoon/"
ln -sFfv "$PWD/src" "$HOME/.hammerspoon"

echo "FCPX Hacks has been linked to your Hammerspoon directory."