#!/bin/sh

### This script will erase or unlink the existing ~/.hammerspoon directory and 
### link it to the src/ directory, thus automatically providing the latest code.

if [ ! -d "$HOME/.hammerspoon/" ]; then
  echo "Please install Hammerspoon: http://www.hammerspoon.org/"
	exit 1
fi

if [ -L "$HOME/.hammerspoon" ]; then
	echo "Unlinking existing Hammerspoon directory."
	unlink "$HOME/.hammerspoon"
fi

if [ -d "$HOME/.hammerspoon" ]; then
	echo "Deleting existing Hammerspoon directory."
	rm -Rf "$HOME/.hammerspoon"
fi

echo "Linking FCPX Hacks source to Hammerspoon directory."
ln -sFfv "$PWD/src" "$HOME/.hammerspoon"

echo "FCPX Hacks has been linked to your Hammerspoon directory."