#!/bin/sh

### This script will create a new DMG file for distribution

if [ ! -d "build" ]; then
  mkdir build
fi

if [ -e "build/FCPXHacks.dmg" ]; then
	rm "build/FCPXHacks.dmg"
fi

cp -R src build/.hammerspoon

echo "Building the DMG"
dmgbuild -s dmg/settings.py "FCPX Hacks" "build/FCPXHacks.dmg"

if [ $? -eq 0 ]; then
	echo "Attaching the license to the DMG"
	dmg/licenseDMG.py build/FCPXHacks.dmg dmg/license.txt
	open build/FCPXHacks.dmg

	echo "The package is in 'build/FCPXHacks.dmg'"
fi

rm -Rf build/.hammerspoon