--- === cp.adobe.aftereffects.shortcuts ===
---
--- Translations between After Effects shortcuts and Hammerspoon-friendly shortcuts.
local mod = {}

--- cp.adobe.aftereffects.shortcuts.labels -> table
--- Constant
--- Table containing label translations.
mod.labels = {
    --------------------------------------------------------------------------------
    -- NOTE: One day I'd love to actually i18n-ifty these, but to get these values
    --       I had to use Hopper to decompile the After Effects application bundle
    --       as all the strings are within the binary. Also, to install AE in a
    --       different language, you actually need to completely uninstall and
    --       reinstall from the Creative Cloud app - yep, it's a mess.
    --------------------------------------------------------------------------------
	["AE_TopLevelWindow"] = {
		["SelectNextTab"]                                               = "Select Next Panel in Frame",
		["SelectPrevTab"]                                               = "Select Previous Panel in Frame",
		["ToggleTabPanelMaximize"]                                      = "Maximize Panel",
		["ZoomWindowMega"]                                              = "Maximize App Window",
		["ZoomWindowMegaMainMonitor"]                                   = "Maximize App Window on Primary Monitor",
	},

	["CCompCloneCmd"] = {
		["CloneSelectPreset1"]                                          = "Clone Preset 1",
		["CloneSelectPreset2"]                                          = "Clone Preset 2",
		["CloneSelectPreset3"]                                          = "Clone Preset 3",
		["CloneSelectPreset4"]                                          = "Clone Preset 4",
		["CloneSelectPreset5"]                                          = "Clone Preset 5",
	},

	["CCompCmd"] = {
		["AddLayerMarkerWithDialog"]                                    = "Add Layer Marker Using Dialog Box",
		["AddMarker"]                                                   = "Add Layer Marker",
		["CenterAnchorToBounds"]                                        = "Center Anchor Point in Layer Content",
		["CenterLayerInView"]                                           = "Center Layer in View",
		["Clear"]                                                       = "Clear (Delete)",
		["ClearMask"]                                                   = "Clear Mask", -- was just ClearMask
		["FlipHorizontal"]                                              = "Flip Horizontal",
		["FlipVertical"]                                                = "Flip Vertical",
		["OpenSource"]                                                  = "Open Layer Source in Layer Panel",
		["PasteAlt"]                                                    = "Paste Layers at Current Time",
		["ReverseLayer"]                                                = "Reverse Layer",
		["SelectNext"]                                                  = "Select Next Effect",
		["SelectNextAdd"]                                               = "Extend Selection to Next Effect",
		["SelectPrevious"]                                              = "Select Previous Effect",
		["SelectPreviousAdd"]                                           = "Extend Selection to Previous Effect",
		["SetWorkAreaEnd"]                                              = "Set Work Area End",
		["SetWorkAreaStart"]                                            = "Set Work Area Start",
		["SetWorkAreaToSelection"]                                      = "Set Work Area to Selected Layers",
		["StretchLayerToFit"]                                           = "Fit Layer to Comp",
		["StretchLayerToFitHorizontal"]                                 = "Fit Layer to Comp Width",
		["StretchLayerToFitVertical"]                                   = "Fit Layer to Comp Height",
	},

	["CCompCompCmd"] = {
		["CompOpenCompStuff"]                                           = "Open Composition",
		["CompScollSelectedLayerToTop"]                                 = "Scroll Selected Layer to Top",
		["CompScrollToCurrentTime"]                                     = "Scroll to Current Time",
		["CompSelectLayer1"]                                            = "Select Layer by Number: 1",
		["CompSelectLayer2"]                                            = "Select Layer by Number: 2",
		["CompSelectLayer3"]                                            = "Select Layer by Number: 3",
		["CompSelectLayer4"]                                            = "Select Layer by Number: 4",
		["CompSelectLayer5"]                                            = "Select Layer by Number: 5",
		["CompSelectLayer6"]                                            = "Select Layer by Number: 6",
		["CompSelectLayer7"]                                            = "Select Layer by Number: 7",
		["CompSelectLayer8"]                                            = "Select Layer by Number: 8",
		["CompSelectLayer9"]                                            = "Select Layer by Number: 9",
		["CompTimeZoomFrames"]                                          = "Zoom In to Frame Intervals",
		["CompTimeZoomIn"]                                              = "Zoom In",
		["CompTimeZoomOut"]                                             = "Zoom Out",
		["CompTimeZoomToggleFullCustom"]                                = "Toggle Zoom Level",
		["CompToggleEffects"]                                           = "Show/Hide Effects (Double-Tap: Expressions)",
		["CompToggleEffectsAddState"]                                   = "Show/Hide Effects (Extend; Double-Tap: Expressions)",
		["CompToggleMaskFeathers"]                                      = "Show/Hide Mask Feather (Double-Tap)",
		["CompToggleMaskFeathersAddState"]                              = "Show/Hide Mask Feather (Extend; Double-Tap)",
		["CompToggleMaskFeathersAddStateNewKF"]                         = "Add/Delete Mask Feather Keyframe at Current Time",
		["CompToggleMaskFeathersNewKF"]                                 = "CompToggleMaskFeathersNewKF",
		["CompToggleMaskShapes"]                                        = "Show/Hide Mask Shape (Double-Tap)",
		["CompToggleMaskShapesAddState"]                                = "Show/Hide Mask Shape (Extend; Double-Tap)",
		["CompToggleMaskShapesAddStateNewKF"]                           = "Add/Delete Mask Shape Keyframe at Current Time",
		--["CompToggleMaskShapesNewKF"]                                   = "CompToggleMaskShapesNewKF",
		["CompToggleSelectLayer1"]                                      = "Toggle Selection of Layer by Number: 1",
		["CompToggleSelectLayer2"]                                      = "Toggle Selection of Layer by Number: 2",
		["CompToggleSelectLayer3"]                                      = "Toggle Selection of Layer by Number: 3",
		["CompToggleSelectLayer4"]                                      = "Toggle Selection of Layer by Number: 4",
		["CompToggleSelectLayer5"]                                      = "Toggle Selection of Layer by Number: 5",
		["CompToggleSelectLayer6"]                                      = "Toggle Selection of Layer by Number: 6",
		["CompToggleSelectLayer7"]                                      = "Toggle Selection of Layer by Number: 7",
		["CompToggleSelectLayer8"]                                      = "Toggle Selection of Layer by Number: 8",
		["CompToggleSelectLayer9"]                                      = "Toggle Selection of Layer by Number: 9",
		["CompToggleUberAnimatingKeyframes"]                            = "Show/Hide Properties with Keyframes (Double-Tap)",
		["CompToggleUberAnimatingKeyframesAddState"]                    = "Show/Hide Properties with Keyframes (Extend; Double-Tap)",
		["CompToggleUberAnimatingKeyframesAndExpressions"]              = "Show/Hide Properties with Animation (Double-Tap)",
		["CompToggleUberAnimatingKeyframesAndExpressionsAddState"]      = "Show/Hide Properties with Animation (Extend; Double-Tap)",
		["CompTwirlAnchorPoint"]                                        = "Show/Hide Anchor Point or Position of Interest",
		["CompTwirlAnchorPointAddState"]                                = "Show/Hide Anchor Point or Position of Interest (Extend)",
		["CompTwirlAnchorPointAddStateNewKF"]                           = "Add/Delete Anchor Point or Position of Interest Keyframe at Current Time",
		["CompTwirlAnchorPointNewKF"]                                   = "CompTwirlAnchorPointNewKF",
		["CompTwirlAudio"]                                              = "Show/Hide Audio Levels",
		["CompTwirlAudioAddState"]                                      = "Show/Hide Audio Levels (Extend)",
		["CompTwirlAudioAddStateNewKF"]                                 = "Add/Delete Audio Levels Keyframe at Current Time",
		--["CompTwirlAudioNewKF"]                                         = "CompTwirlAudioNewKF",
		["CompTwirlOpacity"]                                            = "Show/Hide Opacity",
		["CompTwirlOpacityAddState"]                                    = "Show/Hide Opacity (Extend)",
		["CompTwirlOpacityAddStateNewKF"]                               = "Add/Delete Opacity Keyframe at Current Time",
		--["CompTwirlOpacityNewKF"]                                       = "CompTwirlOpacityNewKF",
		["CompTwirlPosition"]                                           = "Show/Hide Position",
		["CompTwirlPositionAddState"]                                   = "Show/Hide Position (Extend)",
		["CompTwirlPositionAddStateNewKF"]                              = "Add/Delete Position Keyframe at Current Time",
		--["CompTwirlPositionNewKF"]                                      = "CompTwirlPositionNewKF",
		["CompTwirlRotation"]                                           = "Show/Hide Rotation and Orientation Properties",
		["CompTwirlRotationAddState"]                                   = "Show/Hide Rotation and Orientation Properties (Extend)",
		["CompTwirlRotationAddStateNewKF"]                              = "Add/Delete Rotation or Orientation Keyframe at Current Time",
		--["CompTwirlRotationNewKF"]                                      = "CompTwirlRotationNewKF",
		["CompTwirlScale"]                                              = "Show/Hide Scale",
		["CompTwirlScaleAddState"]                                      = "Show/Hide Scale (Extend)",
		["CompTwirlScaleAddStateNewKF"]                                 = "Add/Delete Scale Keyframe at Current Time",
		--["CompTwirlScaleNewKF"]                                         = "CompTwirlScaleNewKF",
		["NextKeyframe"]                                                = "Go to Next Keyframe",
		["NudgeDown"]                                                   = "Move Layer 1 Screen Pixel Down",
		["NudgeDownMore"]                                               = "Move Layer 10 Screen Pixels Down",
		["NudgeEarlier"]                                                = "Shift Layer 1 Frame Earlier",
		["NudgeEarlierMore"]                                            = "Shift Layer 10 Frames Earlier",
		["NudgeKeyframesEarlier"]                                       = "Shift Selected Keyframes 1 Frame Earlier",
		["NudgeKeyframesEarlierMore"]                                   = "Shift Selected Keyframes 10 Frames Earlier",
		["NudgeKeyframesLater"]                                         = "Shift Selected Keyframes 1 Frame Later",
		["NudgeKeyframesLaterMore"]                                     = "Shift Selected Keyframes 10 Frames Later",
		["NudgeLater"]                                                  = "Shift Layer 1 Frame Later",
		["NudgeLaterMore"]                                              = "Shift Layer 10 Frames Later",
		["NudgeLeft"]                                                   = "Move Layer 1 Screen Pixel to the Left",
		["NudgeLeftMore"]                                               = "Move Layer 10 Screen Pixels to the Left",
		["NudgeOpacityDown"]                                            = "Decrease Layer Opacity by 1%",
		["NudgeOpacityDownMore"]                                        = "Decrease Layer Opacity by 10%",
		["NudgeOpacityUp"]                                              = "Increase Layer Opacity by 1%",
		["NudgeOpacityUpMore"]                                          = "Increase Layer Opacity by 10%",
		["NudgeRight"]                                                  = "Move Layer 1 Screen Pixel to the Right",
		["NudgeRightMore"]                                              = "Move Layer 10 Screen Pixels to the Right",
		["NudgeRotCCW"]                                                 = "Rotate Layer 1 Degree Counterclockwise",
		["NudgeRotCCWMore"]                                             = "Rotate Layer 10 Degrees Counterclockwise",
		["NudgeRotCW"]                                                  = "Rotate Layer 1 Degree Clockwise",
		["NudgeRotCWMore"]                                              = "Rotate Layer 10 Degrees Clockwise",
		["NudgeScaleLarger"]                                            = "Scale Layer 1% Larger",
		["NudgeScaleLargerMore"]                                        = "Scale Layer 10% Larger",
		["NudgeScaleSmaller"]                                           = "Scale Layer 1% Smaller",
		["NudgeScaleSmallerMore"]                                       = "Scale Layer 10% Smaller",
		["NudgeUp"]                                                     = "Move Layer 1 Screen Pixel Up",
		["NudgeUpMore"]                                                 = "Move Layer 10 Screen Pixels Up",
		["PrevKeyframe"]                                                = "Go to Previous Keyframe",
		["SelectAllVisibleKeyframes"]                                   = "Select All Visible Keyframes and Exposed Properties",
		["TemporalAlignEnd"]                                            = "Align Selected Layers' In Points to End of Composition",
		["TemporalAlignStart"]                                          = "Align Selected Layers' In Points to Start of Composition",
		["ToggleGraph"]                                                 = "Show/Hide Graph Editor",
		["ToggleTlwParentColumn"]                                       = "Show/Hide Parent Column",
		["Twirl"]                                                       = "Twirl",
		["TwirlExplode"]                                                = "Show/Hide All of the Selected Layers' Properties",
		--["TwirlPreserveSolo"]                                           = "TwirlPreserveSolo",
		--["TwirlPreserveSoloExplode"]                                    = "TwirlPreserveSoloExplode",
	},

    ["CCompMarkerCmd"] = {
        ["CompGotoMarker0"]                                             = "Go to Composition Marker '0'",
        ["CompGotoMarker1"]                                             = "Go to Composition Marker '1'",
        ["CompGotoMarker2"]                                             = "Go to Composition Marker '2'",
        ["CompGotoMarker3"]                                             = "Go to Composition Marker '3'",
        ["CompGotoMarker4"]                                             = "Go to Composition Marker '4'",
        ["CompGotoMarker5"]                                             = "Go to Composition Marker '5'",
        ["CompGotoMarker6"]                                             = "Go to Composition Marker '6'",
        ["CompGotoMarker7"]                                             = "Go to Composition Marker '7'",
        ["CompGotoMarker8"]                                             = "Go to Composition Marker '8'",
        ["CompGotoMarker9"]                                             = "Go to Composition Marker '9'",
        ["CompMarker0"]                                                 = "Create Composition Marker '0'",
        ["CompMarker1"]                                                 = "Create Composition Marker '1'",
        ["CompMarker2"]                                                 = "Create Composition Marker '2'",
        ["CompMarker3"]                                                 = "Create Composition Marker '3'",
        ["CompMarker4"]                                                 = "Create Composition Marker '4'",
        ["CompMarker5"]                                                 = "Create Composition Marker '5'",
        ["CompMarker6"]                                                 = "Create Composition Marker '6'",
        ["CompMarker7"]                                                 = "Create Composition Marker '7'",
        ["CompMarker8"]                                                 = "Create Composition Marker '8'",
        ["CompMarker9"]                                                 = "Create Composition Marker '9'",
    },

    ["CCompPaintCmd"] = {
        ["PaintColorResetBW"]                                           = "Reset Foreground/Background to Black/White",
        ["PaintColorSwapFgBg"]                                          = "Swap Foreground/Background Colors",
        ["PaintSetFlow10"]                                              = "Set Paint Flow to 10%",
        ["PaintSetFlow100"]                                             = "Set Paint Flow to 100%",
        ["PaintSetFlow20"]                                              = "Set Paint Flow to 20%",
        ["PaintSetFlow30"]                                              = "Set Paint Flow to 30%",
        ["PaintSetFlow40"]                                              = "Set Paint Flow to 40%",
        ["PaintSetFlow50"]                                              = "Set Paint Flow to 50%",
        ["PaintSetFlow60"]                                              = "Set Paint Flow to 60%",
        ["PaintSetFlow70"]                                              = "Set Paint Flow to 70%",
        ["PaintSetFlow80"]                                              = "Set Paint Flow to 80%",
        ["PaintSetFlow90"]                                              = "Set Paint Flow to 90%",
        ["PaintSetOpacity10"]                                           = "Set Paint Opacity to 10%",
        ["PaintSetOpacity100"]                                          = "Set Paint Opacity to 100%",
        ["PaintSetOpacity20"]                                           = "Set Paint Opacity to 20%",
        ["PaintSetOpacity30"]                                           = "Set Paint Opacity to 30%",
        ["PaintSetOpacity40"]                                           = "Set Paint Opacity to 40%",
        ["PaintSetOpacity50"]                                           = "Set Paint Opacity to 50%",
        ["PaintSetOpacity60"]                                           = "Set Paint Opacity to 60%",
        ["PaintSetOpacity70"]                                           = "Set Paint Opacity to 70%",
        ["PaintSetOpacity80"]                                           = "Set Paint Opacity to 80%",
        ["PaintSetOpacity90"]                                           = "Set Paint Opacity to 90%",
        ["PaintTimeStepBack"]                                           = "Paint Tools - Go Back by Stroke Duration",
        ["PaintTimeStepForward"]                                        = "Paint Tools - Go Forward by Stroke Duration",
    },

    ["CCompTime"] = {
        ["TimeFastForward"]                                             = "Go to End of Composition, Layer, or Footage Item",
        ["TimeJumpToIn"]                                                = "Go to In Point",
        ["TimeJumpToNextInOut"]                                         = "Go to Next Layer In or Out Point",
        ["TimeJumpToOut"]                                               = "Go to Out Point",
        ["TimeJumpToPrevInOut"]                                         = "Go to Previous Layer In or Out Point",
        ["TimeJumpToWAEnd"]                                             = "Go to End of Work Area",
        ["TimeJumpToWAStart"]                                           = "Go to Start of Work Area",
        ["TimeRewind"]                                                  = "Go to Start of Composition, Layer, or Footage Item",
        ["TimeSetIn"]                                                   = "Set Layer In Point at Current Time",
        ["TimeSetOut"]                                                  = "Set Layer Out Point at Current Time",
        ["TimeShiftSpacebarPlay"]                                       = "Preview (Time Shift)",
        ["TimeSpacebarPlay"]                                            = "Preview",
        ["TimeStepBack"]                                                = "Go to Previous Frame",
        ["TimeStepBackMore"]                                            = "Go Back 10 Frames",
        ["TimeStepForward"]                                             = "Go Forward 1 Frame",
        ["TimeStepForwardMore"]                                         = "Go Forward 10 Frames",
        ["TimeStretchIn"]                                               = "Stretch Layer In Point to Current Time",
        ["TimeStretchOut"]                                              = "Stretch Layer Out Point to Current Time",
        ["TimeTrimIn"]                                                  = "Trim Layer In Point to Current Time",
        ["TimeTrimOut"]                                                 = "Trim Layer Out Point to Current Time",
    },

    ["CDirItemTabPanelTime"] = {
        ["TimeFastForward"]                                             = "Go to End of Composition",
        ["TimeRewind"]                                                  = "Go to Start of Composition",
        ["TimeShiftSpacebarPlay"]                                       = "Preview (Time Shift)",
        ["TimeSpacebarPlay"]                                            = "Preview",
        ["TimeStepBack"]                                                = "Go to Previous Frame",
        ["TimeStepBackMore"]                                            = "Go Back 10 Frames",
        ["TimeStepForward"]                                             = "Go Forward 1 Frame",
        ["TimeStepForwardMore"]                                         = "Go Forward 10 Frames",
    },

    ["CDirTabPanel"] = {
        ["NewViewer"]                                                   = "New Viewer",
        ["NewViewerNewFrame"]                                           = "Split New Viewer, and Toggle Lock",
        ["OpenMiniFlowPopup"]                                           = "Show/Hide Composition Mini-Flowchart",
    },

    ["CEggApp"] = {
        ["BrowseInBridge"]                                              = "Browse in Bridge",
        ["CancelAllPreviews"]                                           = "Cancel Preview",
        ["New"]                                                         = "New Project",
        ["OpenComp"]                                                    = "Switch to Composition Panel",
        ["OpenMRUContext"]                                              = "Switch Between Current and Last Accessed Composition",
        ["PreviewAudio"]                                                = "Audio Preview (Here Forward)",
        ["PreviewAudioWorkArea"]                                        = "Audio Preview (Work Area)",
        ["PreviewNumpad0"]                                              = "Preview (Numpad)",
       -- ["PreviewNumpad0NFrames"]                                       = "PreviewNumpad0NFrames",
        ["PreviewShiftNumpad0"]                                         = "Preview (Shift Numpad)",
        ["ShowConsole"]                                                 = "Show Console",
        ["ShowDebugMonitor"]                                            = "Show Debug Monitor",
        ["ToggleTransmit"]                                              = "Show Current Frame on External Monitor",
        --["WriteKeybindingsFile"]                                        = "WriteKeybindingsFile",
        --["WriteStringFile"]                                             = "WriteStringFile",
        --["WriteVersionFile"]                                            = "WriteVersionFile",
        --["WriteVersionFileExtra"]                                       = "WriteVersionFileExtra",
    },

    ["CEggAppTool"] = {
        ["ToolArrow"]                                                   = "Selection",
        ["ToolCamera"]                                                  = "Camera (Cycle Forward)",
        ["ToolCameraToggle"]                                            = "Camera (Cycle Backward)",
        ["ToolHand"]                                                    = "Hand",
        ["ToolMagnify"]                                                 = "Zoom",
        ["ToolMask"]                                                    = "Shape / Mask (Cycle Forward)",
        ["ToolMaskToggle"]                                              = "Shape / Mask (Cycle Backward)",
        ["ToolPaint"]                                                   = "Paint (Brush/Clone/Eraser)",
        ["ToolPan"]                                                     = "Pan Behind (Anchor Point)",
        ["ToolPen"]                                                     = "Pen / Mask Feather (Cycle Forward)",
        ["ToolPenToggle"]                                               = "Pen / Mask Feather (Cycle Backward)",
        ["ToolPin"]                                                     = "Puppet (Pin/Overlap/Starch)",
        ["ToolRotate"]                                                  = "Rotate",
        ["ToolRotoBrush"]                                               = "Roto Brush / Refine Edge",
        ["ToolText"]                                                    = "Text",
    },

    ["CItem"] = {
        ["FastPreviewsAdaptiveResolution"]                              = "Switch Fast Preview to Adaptive Resolution",
        ["FastPreviewsDraft"]                                           = "Switch Fast Preview to Draft",
        ["FastPreviewsFastDraft"]                                       = "Switch Fast Preview to Fast Draft",
        ["FastPreviewsOff"]                                             = "Switch Fast Preview to Off (Final Quality)",
        ["FastPreviewsWireframe"]                                       = "Switch Fast Preview to Wireframe",
        ["PurgeSnapshot1"]                                              = "Purge Snapshot 1",
        ["PurgeSnapshot2"]                                              = "Purge Snapshot 2",
        ["PurgeSnapshot3"]                                              = "Purge Snapshot 3",
        ["PurgeSnapshot4"]                                              = "Purge Snapshot 4",
        ["ShowAlphaChannel"]                                            = "Show/Hide Alpha Channel (Grayscale)",
        ["ShowAlphaChannelAlt"]                                         = "Show/Hide RGB Straight Color",
        ["ShowAlphaOutline"]                                            = "Toggle Alpha Boundary",
        ["ShowAlphaOverlay"]                                            = "Toggle Alpha Overlay",
        ["ShowBlueChannel"]                                             = "Show/Hide Blue Channel (Grayscale)",
        ["ShowBlueChannelAlt"]                                          = "Show/Hide Blue Channel (Colorized)",
        ["ShowGreenChannel"]                                            = "Show/Hide Green Channel (Grayscale)",
        ["ShowGreenChannelAlt"]                                         = "Show/Hide Green Channel (Colorized)",
        ["ShowRedChannel"]                                              = "Show/Hide Red Channel (Grayscale)",
        ["ShowRedChannelAlt"]                                           = "Show/Hide Red Channel (Colorized)",
        ["ShowSnapshot1"]                                               = "Show Snapshot 1",
        ["ShowSnapshot2"]                                               = "Show Snapshot 2",
        ["ShowSnapshot3"]                                               = "Show Snapshot 3",
        ["ShowSnapshot4"]                                               = "Show Snapshot 4",
        ["ShowXray"]                                                    = "Toggle Refine Edge X-ray",
        ["TakeSnapshot1"]                                               = "Take Snapshot 1",
        ["TakeSnapshot2"]                                               = "Take Snapshot 2",
        ["TakeSnapshot3"]                                               = "Take Snapshot 3",
        ["TakeSnapshot4"]                                               = "Take Snapshot 4",
        ["TitleActionGridAnim"]                                         = "Show/Hide Proportional Grid",
        ["TitleActionGridRotate"]                                       = "Show/Hide Title/Action Safe Guides",
        ["TitleActionSafeToggle"]                                       = "Show/Hide Grid",
        --["VOutPushFrame"]                                               = "VOutPushFrame",
    },

    ["COutline"] = {
        ["Clear"]                                                       = "Clear",
        ["Rename"]                                                      = "Rename",
    },

    ["CPanoECOutline"] = {
        --["NOP"]                                                         = "NOP",
        ["OpenComp"]                                                    = "Switch to Composition Panel",
        ["SelectNext"]                                                  = "Select Next Project Item",
        ["SelectNextAdd"]                                               = "Extend Selection to Next Project Item",
        ["SelectPrevious"]                                              = "Select Previous Project Item",
        ["SelectPreviousAdd"]                                           = "Extend Selection to Previous Project Item",
        ["TwirlClosed"]                                                 = "Collapse Selected Folder",
        ["TwirlOpen"]                                                   = "Expand Selected Folder",
    },

    ["CPanoProjFootage"] = {
        ["TimeJumpToIn"]                                                = "Go to In Point",
        ["TimeJumpToOut"]                                               = "Go to Out Point",
        ["TimeStepBack"]                                                = "Go to Previous Frame",
        ["TimeStepForward"]                                             = "Go to Next Frame",
        ["TimeTrimIn"]                                                  = "Set In Point at Current Time",
        ["TimeTrimOut"]                                                 = "Set Out Point at Current Time",
    },

    ["CPanoProjItem"] = {
        ["FitItemView"]                                                 = "Fit",
        ["FitItemViewUpTo100"]                                          = "Fit up to 100%",
        ["GizmoModeCombined"]                                           = "3D Combined Gizmo",
        ["GizmoModeLegacy"]                                             = "3D Wireframe Gizmo",
        ["GizmoModeRotate"]                                             = "3D Rotation Gizmo",
        ["GizmoModeScale"]                                              = "3D Scale Gizmo",
        ["GizmoModeTranslate"]                                          = "3D Translation Gizmo",
        ["ProofColors"]                                                 = "Enable/Disable Display Color Management",
        ["SelectNextMask"]                                              = "Select Next Mask",
        ["SelectPreviousMask"]                                          = "Select Previous Mask",
        ["Zoom100Percent"]                                              = "Zoom to 100%",
        ["ZoomIn"]                                                      = "Zoom In",
        ["ZoomInResize"]                                                = "Zoom In & Resize", -- was just ZoomInResize
        ["ZoomNoScroll"]                                                = "ZoomNoScroll",
        ["ZoomOut"]                                                     = "Zoom Out",
        ["ZoomOutResize"]                                               = "Zoom Out & Resize", -- was just ZoomOutResize
    },

    ["CPanoProjLayer"] = {
        ["Clear"]                                                       = "Clear",
        ["ClearMask"]                                                   = "Clear Mask", -- was just ClearMask
        ["OpenComp"]                                                    = "Switch to Composition Panel",
        ["TimeSetIn"]                                                   = "Set Layer In Point at Current Time",
        ["TimeSetOut"]                                                  = "Set Layer Out Point at Current Time",
        ["TimeStretchIn"]                                               = "Stretch Layer In Point to Current Time",
        ["TimeStretchOut"]                                              = "Stretch Layer Out Point to Current Time",
        ["TimeTrimIn"]                                                  = "Trim Layer In Point to Current Time",
        ["TimeTrimOut"]                                                 = "Trim Layer Out Point to Current Time",
    },

    ["CPanoProjLayerPano"] = {
        ["NudgeDown"]                                                   = "Move Layer 1 Screen Pixel Down",
        ["NudgeDownMore"]                                               = "Move Layer 10 Screen Pixels Down",
        ["NudgeLeft"]                                                   = "Move Layer 1 Screen Pixel to the Left",
        ["NudgeLeftMore"]                                               = "Move Layer 10 Screen Pixels to the Left",
        ["NudgeOpacityDown"]                                            = "Decrease Layer Opacity by 1%",
        ["NudgeOpacityDownMore"]                                        = "Decrease Layer Opacity by 10%",
        ["NudgeOpacityUp"]                                              = "Increase Layer Opacity by 1%",
        ["NudgeOpacityUpMore"]                                          = "Increase Layer Opacity by 10%",
        ["NudgeRight"]                                                  = "Move Layer 1 Screen Pixel to the Right",
        ["NudgeRightMore"]                                              = "Move Layer 10 Screen Pixels to the Right",
        ["NudgeRotCCW"]                                                 = "Rotate Layer 1 Degree Counterclockwise",
        ["NudgeRotCCWMore"]                                             = "Rotate Layer 10 Degrees Counterclockwise",
        ["NudgeRotCW"]                                                  = "Rotate Layer 1 Degree Clockwise",
        ["NudgeRotCWMore"]                                              = "Rotate Layer 10 Degrees Clockwise",
        ["NudgeScaleLarger"]                                            = "Scale Layer 1% Larger",
        ["NudgeScaleLargerMore"]                                        = "Scale Layer 10% Larger",
        ["NudgeScaleSmaller"]                                           = "Scale Layer 1% Smaller",
        ["NudgeScaleSmallerMore"]                                       = "Scale Layer 10% Smaller",
        ["NudgeUp"]                                                     = "Move Layer 1 Screen Pixel Up",
        ["NudgeUpMore"]                                                 = "Move Layer 10 Screen Pixels Up",
    },

    ["CPanoProjLayerPanoMask"] = {
        ["Zoom100Percent"]                                              = "Zoom to 100%",
        ["ZoomIn"]                                                      = "Zoom In",
        ["ZoomOut"]                                                     = "Zoom Out",
    },

    ["CPanoRender"] = {
        ["StopRenderQueue"]                                             = "Stop Render Queue", -- was just StopRenderQueue
    },

    ["CSwitchboard"] = {
        ["AddCompToRenderQueue"]                                        = "Add Comp to Render Queue",
        ["AddItemToComp"]                                               = "Add Footage Item to Comp",
        ["AddItemToCompReplaceLayer"]                                   = "Replace Selected Layer with Selected Footage Item",
        ["AddItemsToNewComp"]                                           = "New Comp from Selection",
        ["AddToAdobeMediaEncoderRenderQueue"]                           = "Add Comp to Adobe Media Encoder Queue",
        ["AutoOrient"]                                                  = "Auto-Orient",
        ["BestQuality"]                                                 = "Set Layer Quality to Best",
        --["BestQualityRecurse"]                                          = "BestQualityRecurse",
        ["BringCloser"]                                                 = "Bring Layer Forward",
        ["BringToFront"]                                                = "Bring Layer to Front",
        ["Clear"]                                                       = "Clear (Delete)",
        ["Close"]                                                       = "Close Current Panel or Viewer Contents",
        ["CloseAll"]                                                    = "Close All", -- was just CloseAll
        ["CloseWindow"]                                                 = "Close Current Viewer or All Viewers of Same Type",
        ["CompSettings"]                                                = "Composition Settings",
        ["CompToggleUberAnimatingKeyframes"]                            = "Show/Hide Properties with Keyframes (Double-Tap)",
        ["CompToggleUberAnimatingKeyframesAddState"]                    = "Show/Hide Properties with Keyframes (Extend; Double-Tap)",
        ["CompToggleUberAnimatingKeyframesAndExpressions"]              = "Show/Hide Properties with Animation (Double-Tap)",
        ["CompToggleUberAnimatingKeyframesAndExpressionsAddState"]      = "Show/Hide Properties with Animation (Extend; Double-Tap)",
        ["CompTrimToWorkArea"]                                          = "Trim Comp to Work Area",
        ["CompViewOptions"]                                             = "View Options",
        ["Compify"]                                                     = "Pre-compose",
        ["Copy"]                                                        = "Copy",
        ["CopyExpressionLinkedInstance"]                                = "Copy with Property Links",
        ["CopyExpressionLinkedInstanceRelative"]                        = "Copy with Relative Property Links",
        ["CustResNoDialog"]                                             = "Set Comp Resolution to Custom",
        ["CustResNoDialogRecurse"]                                      = "CustResNoDialogRecurse",
        ["Cut"]                                                         = "Cut",
        --["DebugDroverCreateNewTab"]                                     = "DebugDroverCreateNewTab",
        ["DeselectAll"]                                                 = "Deselect All Layers",
        ["DeselectAllKeyframes"]                                        = "Deselect All Keyframes and Properties",
        ["DraftQuality"]                                                = "Set Layer Quality to Draft",
        --["DraftQualityRecurse"]                                         = "DraftQualityRecurse",
        ["Duplicate"]                                                   = "Duplicate",
        ["EasyEase"]                                                    = "Set Keyframe to Easy Ease",
        ["EasyEaseIn"]                                                  = "Set Keyframe to Easy Ease In",
        ["EasyEaseOut"]                                                 = "Set Keyframe to Easy Ease Out",
        ["EditFileExternally"]                                          = "Edit Original",
        ["EnableTimeRemap"]                                             = "Enable Time Remapping",
        ["ExecuteScript"]                                               = "Run Script File",
        ["ExecuteScriptMenuItem01"]                                     = "Run Script # 1",
        ["ExecuteScriptMenuItem02"]                                     = "Run Script # 2",
        ["ExecuteScriptMenuItem03"]                                     = "Run Script # 3",
        ["ExecuteScriptMenuItem04"]                                     = "Run Script # 4",
        ["ExecuteScriptMenuItem05"]                                     = "Run Script # 5",
        ["ExecuteScriptMenuItem06"]                                     = "Run Script # 6",
        ["ExecuteScriptMenuItem07"]                                     = "Run Script # 7",
        ["ExecuteScriptMenuItem08"]                                     = "Run Script # 8",
        ["ExecuteScriptMenuItem09"]                                     = "Run Script # 9",
        ["ExecuteScriptMenuItem10"]                                     = "Run Script # 10",
        ["ExecuteScriptMenuItem11"]                                     = "Run Script # 11",
        ["ExecuteScriptMenuItem12"]                                     = "Run Script # 12",
        ["ExecuteScriptMenuItem13"]                                     = "Run Script # 13",
        ["ExecuteScriptMenuItem14"]                                     = "Run Script # 14",
        ["ExecuteScriptMenuItem15"]                                     = "Run Script # 15",
        ["ExecuteScriptMenuItem16"]                                     = "Run Script # 16",
        ["ExecuteScriptMenuItem17"]                                     = "Run Script # 17",
        ["ExecuteScriptMenuItem18"]                                     = "Run Script # 18",
        ["ExecuteScriptMenuItem19"]                                     = "Run Script # 19",
        ["ExecuteScriptMenuItem20"]                                     = "Run Script # 20",
        ["FilterNone"]                                                  = "Delete All Effects from Selected Layers",
        ["Find"]                                                        = "Find (Search Filter)",
        ["FindNext"]                                                    = "Find Next", -- was just FindNext
        ["ForceScanForChangedFootage"]                                  = "Reload Selected Footage Items",
        ["GoToTime"]                                                    = "Go to Time",
        ["Group"]                                                       = "Group Shapes",
        ["HelpAfterEffectsHelp"]                                        = "Help",
        ["HideOtherVideo"]                                              = "Hide Other Layers' Video",
        ["HighResolution"]                                              = "Set Comp Resolution to High",
        --["HighResolutionRecurse"]                                       = "HighResolutionRecurse",
        ["ImportFootage"]                                               = "Import File",
        ["ImportMultiple"]                                              = "Import Multiple Files",
        ["IncrementAndSave"]                                            = "Increment and Save Project",
        ["InterpretFootage"]                                            = "Interpret Footage",
        ["KeyframeInterpDialog"]                                        = "Keyframe Interpolation (Edit in Dialog Box)",
        ["KeyframeVelocityDialog"]                                      = "Keyframe Velocity (Edit in Dialog Box)",
        ["LastEffect"]                                                  = "Apply Last Effect",
        ["LayerSettings"]                                               = "Layer Settings",
        ["LookAtSelected"]                                              = "Move Camera and its POI to Look at Selected Layers",
        ["LowResolution"]                                               = "Set Comp Resolution to Low",
        --["LowResolutionRecurse"]                                        = "LowResolutionRecurse",
        --["MacSysMenuMinimize"]                                          = "MacSysMenuMinimize",
        ["Mask"]                                                        = "Mask Shape (Edit in Dialog Box)",
        ["MaskFeather"]                                                 = "Mask Feather (Edit in Dialog Box)",
        ["MaskInverse"]                                                 = "Invert Mask",
        ["MaskReshape"]                                                 = "Mask Free-Transform",
        ["MedResolution"]                                               = "Set Comp Resolution to Half",
        --["MedResolutionRecurse"]                                        = "MedResolutionRecurse",
        --["MemoryModeToggle"]                                            = "MemoryModeToggle",
        ["New"]                                                         = "New Project",
        ["NewCamera"]                                                   = "New Camera Layer",
        ["NewComp"]                                                     = "New Composition",
        --["NewDebugComp"]                                                = "NewDebugComp",
        ["NewEffectsLayer"]                                             = "New Adjustment Layer",
        ["NewLight"]                                                    = "New Light Layer",
        ["NewMask"]                                                     = "New Mask",
        ["NewNullObject"]                                               = "New Null Object",
        ["NewSolidInComp"]                                              = "New Solid in Comp", -- was just NewSolidInComp
        ["NewTextLayer"]                                                = "New Text Layer",
        ["NextXferMode"]                                                = "Next Layer Blending Mode",
        ["Offset"]                                                      = "Position (Edit in Dialog Box)",
        ["Opacity"]                                                     = "Opacity (Edit in Dialog Box)",
        ["Open"]                                                        = "Open Project",
        ["OpenEffectControls"]                                          = "OpenEffectControls",
        ["OpenKeyboardShortcutsPanel"]                                  = "OpenKeyboardShortcutsPanel",
        ["OpenLayerSourceWindow"]                                       = "OpenLayerSourceWindow",
        ["Orientation"]                                                 = "Orientation (Edit in Dialog Box)",
        ["Paste"]                                                       = "Paste",
        ["PrefsGeneral"]                                                = "Preferences",
        ["PrevXferMode"]                                                = "Previous Layer Blending Mode",
        ["ProjectSettings"]                                             = "Project Settings",
        ["PurgeAllMemory"]                                              = "Purge All Memory",
        ["Quit"]                                                        = "Quit",
        ["RecentFavorite00"]                                            = "Apply Recently Used Animation Preset",
        ["RecentProject00"]                                             = "Open Most Recent Project",
        ["RecentScript00"]                                              = "Open Most Recent Script", -- was just RecentScript00
        ["Redo"]                                                        = "Redo Last Action",
        ["ReplaceFootage"]                                              = "Replace Footage",
        ["RotateAll"]                                                   = "Rotation (Edit in Dialog Box)",
        ["Save"]                                                        = "Save Project",
        ["SaveAs"]                                                      = "Save Project As",
        ["SaveFrameAs"]                                                 = "Save Frame As",
        ["SavePreviewCurrent"]                                          = "Save Current Preview",
        ["SavePreviewShiftNumpad0"]                                     = "Save Shift+Numpad 0 Preview",
        ["ScanForChangedFootage"]                                       = "Scan for Changed Footage",
        ["SelectAll"]                                                   = "Select All",
        ["SelectNextViewerContext"]                                     = "Switch to Next Item in Viewer",
        ["SelectPrevViewerContext"]                                     = "Switch to Previous Item in Viewer",
        ["SendFarther"]                                                 = "Send Layer Backward",
        ["SendToBack"]                                                  = "Send Layer to Back",
        ["SetProxyFile"]                                                = "Set Proxy for Selected Footage Item",
        ["SetSamplingQualityBicubic"]                                   = "Set Layer Sampling Quality to Bicubic",
        ["SetSamplingQualityBilinear"]                                  = "Set Layer Sampling Quality to Bilinear",
        ["ShowCompTree"]                                                = "Show Flowchart for Composition",
        ["ShowFrameFileName"]                                           = "Show File Name of Frame's Footage in Info Panel",
        ["ShowHideAudio"]                                               = "Show/Hide Audio Panel",
        ["ShowHideBrushPal"]                                            = "Show/Hide Brushes Panel",
        ["ShowHideCharPal"]                                             = "Show/Hide Character Panel",
        ["ShowHideFxPal"]                                               = "Show/Hide Effects & Presets Panel",
        ["ShowHideInfo"]                                                = "Show/Hide Info Panel",
        ["ShowHidePaintPal"]                                            = "Show/Hide Paint Panel",
        ["ShowHideParaPal"]                                             = "Show/Hide Paragraph Panel",
        ["ShowHideProject"]                                             = "Show/Hide Project Panel",
        ["ShowHideRenderQueue"]                                         = "Show/Hide Render Queue Panel",
        ["ShowHideTimePanel"]                                           = "Show/Hide Preview Panel",
        ["ShowHideTools"]                                               = "Show/Hide Tools Panel",
        ["ShowProjectTree"]                                             = "Show Flowchart for Project",
        ["ShowRulers"]                                                  = "Toggle Show Rulers",
        ["SplitLayer"]                                                  = "Split Layer at Current Time",
        ["SwitchTo3DViewA"]                                             = "Switch to 3D View A",
        ["SwitchTo3DViewB"]                                             = "Switch to 3D View B",
        ["SwitchTo3DViewC"]                                             = "Switch to 3D View C",
        ["SwitchTo3DViewFirst"]                                         = "SwitchTo3DViewFirst",
        ["SwitchToLast3DView"]                                          = "Switch to Last 3D View",
        ["SwitchToWorkspaceA"]                                          = "Switch to Workspace #1",
        ["SwitchToWorkspaceB"]                                          = "Switch to Workspace #2",
        ["SwitchToWorkspaceC"]                                          = "Switch to Workspace #3",
        ["ToggleCastsShadows"]                                          = "Toggle Casts Shadows for Selected 3D Layers",
        ["ToggleEffectControls"]                                        = "Show/Hide Effect Controls Panel for Selected Layers",
        ["ToggleExpression"]                                            = "Toggle Expression for Selected Properties",
        ["ToggleKeyframeHoldInterp"]                                    = "Toggle Hold Interpolation for Selected Keyframes",
        ["ToggleLayerControls"]                                         = "Toggle Show Layer Controls",
        ["ToggleLock"]                                                  = "Toggle Lock Switch for Selected Layers",
        ["ToggleLockGuides"]                                            = "Toggle Lock Guides",
        ["ToggleShowGrid"]                                              = "Toggle Show Grid",
        ["ToggleShowGuides"]                                            = "Toggle Show Guides",
        ["ToggleSnapGrid"]                                              = "Toggle Snap to Grid",
        ["ToggleSnapGuides"]                                            = "Toggle Snap to Guides",
        ["ToggleSwitchesModes"]                                         = "Toggle Switches / Modes Column",
        ["ToggleVideo"]                                                 = "Toggle Video Switch for Selected Layers",
        ["Undo"]                                                        = "Undo Last Action",
        ["Ungroup"]                                                     = "Ungroup Shapes",
        ["UnlockAllLayers"]                                             = "Unlock All Layers",
        ["WireframeQuality"]                                            = "Set Layer Quality to Wireframe",
        --["WireframeQualityRecurse"]                                     = "WireframeQualityRecurse",
        --["XFactorPreview"]                                              = "XFactorPreview",
        --["XFactorPreviewMisc"]                                          = "XFactorPreviewMisc",
        --["XFactorPreviewStop"]                                          = "XFactorPreviewStop",
    },

    ["CSwitchboardModal"] = {
        ["Clear"]                                                       = "Clear (Delete)",
        ["Copy"]                                                        = "Copy",
        ["Cut"]                                                         = "Cut",
        ["Paste"]                                                       = "Paste",
        ["Redo"]                                                        = "Redo Last Action",
        ["SelectAll"]                                                   = "Select All",
        ["Undo"]                                                        = "Undo Last Action",
    },

    ["CTopic"] = {
        ["Twirl"]                                                       = "Twirl",
        ["TwirlExplode"]                                                = "Show/Hide All of the Selected Layers' Properties",
        --["TwirlPreserveSolo"]                                           = "TwirlPreserveSolo",
        --["TwirlPreserveSoloExplode"]                                    = "TwirlPreserveSoloExplode",
    },

    ["CameraToolUI"] = {
        ["LookAtAll"]                                                   = "Move Camera to Look At All Layers",
        ["LookAtSelected"]                                              = "Move Camera to Look At Selected Layers",
    },

    ["FloPano"] = {
        ["Clear"]                                                       = "Delete",
        ["ClearWithoutWarning"]                                         = "ClearWithoutWarning",
        ["OpenComp"]                                                    = "Switch to Composition Panel",
        ["Zoom100Percent"]                                              = "Zoom to 100%",
        ["ZoomIn"]                                                      = "Zoom In",
        ["ZoomOut"]                                                     = "Zoom Out",
    },

    --[[
    ["MacSysShortcutsAlt"] = {
        ["MacSysMenuHideMe"]                                            = "MacSysMenuHideMe",
        ["MacSysMenuHideOthers"]                                        = "MacSysMenuHideOthers",
        ["MacSysMenuMinimize"]                                          = "MacSysMenuMinimize",
    },

    ["MacSysShortcutsStd"] = {
        ["MacSysMenuHideMe"]                                            = "MacSysMenuHideMe",
        ["MacSysMenuHideOthers"]                                        = "MacSysMenuHideOthers",
        ["MacSysMenuMinimize"]                                          = "MacSysMenuMinimize",
    },
    --]]

    ["POutlinePano"] = {
        ["AddItemToComp"]                                               = "Add Project Item to Current Composition",
        ["AddItemToCompReplaceLayer"]                                   = "Replace Selected Layers with Selected Project Item",
        ["ApplyInterpretation"]                                         = "Apply Remembered Interpretation of Footage Item",
        ["ClearWithoutWarning"]                                         = "Delete Without Confirmation",
        ["NewFolder"]                                                   = "New Folder",
        ["OpenItemWindow"]                                              = "Open Footage Item in Footage Panel",
        ["RememberInterpretation"]                                      = "Remember Interpretation of Footage Item",
        ["SelectNext"]                                                  = "Select Next Project Item",
        ["SelectNextAdd"]                                               = "Extend Selection to Next Project Item",
        ["SelectPrevious"]                                              = "Select Previous Project Item",
        ["SelectPreviousAdd"]                                           = "Extend Selection to Previous Project Item",
        ["TwirlClosed"]                                                 = "Collapse Selected Folder",
        ["TwirlOpen"]                                                   = "Expand Selected Folder",
    },

    ["RQOutlinePano"] = {
        ["SelectNext"]                                                  = "Select Previous RQ Item or Output Module",
        ["SelectNextAdd"]                                               = "Extend Selection to Next RQ Item or Output Module",
        ["SelectPrevious"]                                              = "Select Previous RQ Item or Output Module",
        ["SelectPreviousAdd"]                                           = "Extend Selection to Previous RQ Item or Output Module",
        ["StartRenderQueue"]                                            = "Start Render",
        ["StopRenderQueue"]                                             = "Stop Render",
        ["TwirlClosed"]                                                 = "Collapse Selected Render Queue Item",
        ["TwirlOpen"]                                                   = "Expand Selected Render Queue Item",
    },

    ["TLOutlinePano"] = {
        ["CompTimeZoomFrames"]                                          = "Zoom In to Frame Intervals",
        ["CompTimeZoomIn"]                                              = "Zoom In to Current Time",
        ["CompTimeZoomOut"]                                             = "Zoom Out from Current Time",
        ["CompTimeZoomToggleFullCustom"]                                = "Toggle Zoom Level",
        ["TimeSetIn"]                                                   = "Set Layer In Point at Current Time",
        ["TimeSetOut"]                                                  = "Set Layer Out Point at Current Time",
        ["TimeStretchIn"]                                               = "Stretch Layer In Point to Current Time",
        ["TimeStretchOut"]                                              = "Stretch Layer Out Point to Current Time",
        ["TimeTrimIn"]                                                  = "Trim Layer In Point to Current Time",
        ["TimeTrimOut"]                                                 = "Trim Layer Out Point to Current Time",
        ["ToggleGraph"]                                                 = "Show/Hide Graph Editor",
    },

    ["TextLayerUI"] = {
        ["TextAlignCenter"]                                             = "Align Selected Text Center (Horiz or Vert)",
        ["TextAlignLeft"]                                               = "Align Selected Text Left (Horiz) or Top (Vert)",
        ["TextAlignRight"]                                              = "Align Selected Text Right (Horiz) or Bottom (Vert)",
        ["TextAllCaps"]                                                 = "Toggle All Caps for Selected Text",
        ["TextAutoLeading"]                                             = "Auto Leading for Selected Text",
        ["TextCancel"]                                                  = "Cancel Changes to Text",
        ["TextCommit"]                                                  = "Commit Changes to Text",
        ["TextCursorToDocumentEnd"]                                     = "Move Insertion Point to End of Text Frame",
        ["TextCursorToDocumentStart"]                                   = "Move Insertion Point to Beginning of Text Frame",
        ["TextCursorToDown"]                                            = "Move Insertion Point to Next Line (Horiz) or Char (Vert)",
        ["TextCursorToLeft"]                                            = "Move Insertion Point to Previous Char (Horiz) or Line (Vert)",
        ["TextCursorToLineEnd"]                                         = "Move Insertion Point to End of Line",
        ["TextCursorToLineStart"]                                       = "Move Insertion Point to Beginning of Line",
        ["TextCursorToRight"]                                           = "Move Insertion Point to Next Char (Horiz) or Line (Vert)",
        ["TextCursorToUp"]                                              = "Move Insertion Point to Previous Line (Horiz) or Char (Vert)",
        ["TextCursorToWordDown"]                                        = "Move Insertion Point to Next Paragraph (Horiz) or Word (Vert)",
        ["TextCursorToWordLeft"]                                        = "Move Insertion Point to Previous Word (Horiz) or Paragraph (Vert)",
        ["TextCursorToWordRight"]                                       = "Move Insertion Point to Next Word (Horiz) or Paragraph (Vert)",
        ["TextCursorToWordUp"]                                          = "Move Insertion Point to Previous Paragraph (Horiz) or Word (Vert)",
        ["TextDecreaseBaselineShift"]                                   = "Decrease Baseline Shift by 2 px",
        ["TextDecreaseBaselineShiftALot"]                               = "Decrease Baseline Shift by 10 px",
        ["TextDecreaseFontSize"]                                        = "Decrease Font Size by 2 px",
        ["TextDecreaseFontSizeALot"]                                    = "Decrease Font Size by 10 px",
        ["TextDecreaseKerning"]                                         = "Decrease Kerning or Tracking by 20 units",
        ["TextDecreaseKerningALot"]                                     = "Decrease Kerning or Tracking by 100 units",
        ["TextDecreaseLeading"]                                         = "Decrease Leading by 2 px",
        ["TextDecreaseLeadingALot"]                                     = "Decrease Leading by 10 px",
        ["TextDeleteBackward"]                                          = "Backspace (Previous Character)",
        ["TextDeleteForward"]                                           = "Delete (Next Character)",
        --["TextIgnoreKey"]                                               = "~~~",
        ["TextIncreaseBaselineShift"]                                   = "Increase Baseline Shift by 2 px",
        ["TextIncreaseBaselineShiftALot"]                               = "Increase Baseline Shift by 10 px",
        ["TextIncreaseFontSize"]                                        = "Increase Font Size by 2 px",
        ["TextIncreaseFontSizeALot"]                                    = "Increase Font Size by 10 px",
        ["TextIncreaseKerning"]                                         = "Increase Kerning or Tracking by 20 px",
        ["TextIncreaseKerningALot"]                                     = "Increase Kerning or Tracking by 100 px",
        ["TextIncreaseLeading"]                                         = "Increase Leading by 2 px",
        ["TextIncreaseLeadingALot"]                                     = "Increase Leading by 10 px",
        ["TextJustifyAll"]                                              = "Justify Paragraph; Force Last Line",
        ["TextJustifyLeft"]                                             = "Justify Paragraph; Left Align Last Line",
        ["TextJustifyRight"]                                            = "Justify Paragraph; Right Align Last Line",
        ["TextResetHorizontalScale"]                                    = "Reset Horizontal Scale of Selected Text",
        ["TextResetTracking"]                                           = "Reset Tracking of Selected Text",
        ["TextResetVerticalScale"]                                      = "Reset Vertical Scale of Selected Text",
        ["TextSelectToDocumentEnd"]                                     = "Extend Selection to End of Text Frame",
        ["TextSelectToDocumentStart"]                                   = "Extend Selection to Beginning of Text Frame",
        ["TextSelectToDown"]                                            = "Extend Selection 1 Line Down (Horiz) or 1 Char Down (Vert)",
        ["TextSelectToLeft"]                                            = "Extend Selection 1 Char to Left (Horiz) or 1 Line to Left (Vert)",
        ["TextSelectToLineEnd"]                                         = "Extend Selection to End of Line",
        ["TextSelectToLineStart"]                                       = "Extend Selection to Beginning of Line",
        ["TextSelectToRight"]                                           = "Extend Selection 1 Char to Right (Horiz) or 1 Line to Right (Vert)",
        ["TextSelectToUp"]                                              = "Extend Selection 1 Line Up (Horiz) or 1 Char Up (Vert)",
        ["TextSelectToWordDown"]                                        = "Extend Selection 1 Word Down (Vert)",
        ["TextSelectToWordLeft"]                                        = "Extend Selection 1 Word to Left (Horiz)",
        ["TextSelectToWordRight"]                                       = "Extend Selection 1 Word to Right (Horiz)",
        ["TextSelectToWordUp"]                                          = "Extend Selection 1 Word Up (Vert)",
        ["TextSmallCaps"]                                               = "Toggle Small Caps for Selected Text",
        ["TextSubScript"]                                               = "Toggle Subscript for Selected Text",
        ["TextSuperScript"]                                             = "Toggle Superscript for Selected Text",
        ["TextToggleComposer"]                                          = "Toggle Composer for Selected Paragraphs",
    },

    ["Tracker"] = {
        ["MTNudgeDown"]                                                 = "Move Track Point Down 1 Screen Pixel",
        ["MTNudgeDownHoldPos"]                                          = "Move Track Point (Not Attach Point) Down 1 Screen Pixel",
        ["MTNudgeDownHoldPosMore"]                                      = "Move Track Point (Not Attach Point) Down 10 Screen Pixels",
        ["MTNudgeDownMore"]                                             = "Move Track Point Down 10 Screen Pixels",
        ["MTNudgeLeft"]                                                 = "Move Track Point Left 1 Screen Pixel",
        ["MTNudgeLeftHoldPos"]                                          = "Move Track Point (Not Attach Point) Left 1 Screen Pixel",
        ["MTNudgeLeftHoldPosMore"]                                      = "Move Track Point (Not Attach Point) Left 10 Screen Pixels",
        ["MTNudgeLeftMore"]                                             = "Move Track Point Left 10 Screen Pixels",
        ["MTNudgeRight"]                                                = "Move Track Point Right 1 Screen Pixel",
        ["MTNudgeRightHoldPos"]                                         = "Move Track Point (Not Attach Point) Right 1 Screen Pixel",
        ["MTNudgeRightHoldPosMore"]                                     = "Move Track Point (Not Attach Point) Right 10 Screen Pixels",
        ["MTNudgeRightMore"]                                            = "Move Track Point Right 10 Screen Pixels",
        ["MTNudgeUp"]                                                   = "Move Track Point Up 1 Screen Pixel",
        ["MTNudgeUpHoldPos"]                                            = "Move Track Point (Not Attach Point) Up 1 Screen Pixel",
        ["MTNudgeUpHoldPosMore"]                                        = "Move Track Point (Not Attach Point) Up 10 Screen Pixels",
        ["MTNudgeUpMore"]                                               = "Move Track Point Up 10 Screen Pixels",
        ["MTSetEnd"]                                                    = "Set Out Point of 'Motion Tracker Points' Bar in Layer Panel",
        ["MTSetStart"]                                                  = "Set In Point of 'Motion Tracker Points' Bar in Layer Panel",
    },
}

--- cp.adobe.aftereffects.shortcuts.keys -> table
--- Constant
--- Table containing key translations.
mod.keys = {
    ["Delete"]          = "delete",
    ["Tab"]             = "tab",
    ["Return"]          = "return",
    ["Esc"]             = "escape",
    ["LeftArrow"]       = "left",
    ["RightArrow"]      = "right",
    ["UpArrow"]         = "up",
    ["DownArrow"]       = "down",
    ["Space"]           = "space",
    ["!"]               = "!",
    ["DoubleQuote"]     = [["]],
    ["SingleQuote"]     = "'",
    ["Comma"]           = ",",
    ["-"]               = "-",
    ["."]               = ".",
    ["/"]               = "/",
    ["0"]               = "0",
    ["1"]               = "1",
    ["2"]               = "2",
    ["3"]               = "3",
    ["4"]               = "4",
    ["5"]               = "5",
    ["6"]               = "6",
    ["7"]               = "7",
    ["8"]               = "8",
    ["9"]               = "9",
    [":"]               = "",
    [";"]               = ";",
    ["<"]               = ",",
    ["="]               = "=",
    ["A"]               = "a",
    ["B"]               = "b",
    ["C"]               = "c",
    ["D"]               = "d",
    ["E"]               = "e",
    ["F"]               = "f",
    ["G"]               = "g",
    ["H"]               = "h",
    ["I"]               = "i",
    ["J"]               = "j",
    ["K"]               = "k",
    ["L"]               = "l",
    ["M"]               = "m",
    ["N"]               = "n",
    ["O"]               = "o",
    ["P"]               = "p",
    ["Q"]               = "q",
    ["R"]               = "r",
    ["S"]               = "s",
    ["T"]               = "t",
    ["U"]               = "u",
    ["V"]               = "v",
    ["W"]               = "w",
    ["X"]               = "x",
    ["Y"]               = "y",
    ["Z"]               = "z",
    ["["]               = "[",
    ["]"]               = "]",
    ["`"]               = "`",
    ["PadDecimal"]      = "",
    ["PadComma"]        = "pad,",
    ["PadMultiply"]     = "pad*",
    ["PadPlus"]         = "pad+",
    ["PadClear"]        = "padclear",
    ["PadSlash"]        = "pad/",
    ["PadMinus"]        = "pad-",
    ["PadEqual"]        = "pad=",
    ["Pad0"]            = "pad0",
    ["Pad1"]            = "pad1",
    ["Pad2"]            = "pad2",
    ["Pad3"]            = "pad3",
    ["Pad4"]            = "pad4",
    ["Pad5"]            = "pad5",
    ["Pad6"]            = "pad6",
    ["Pad7"]            = "pad7",
    ["Pad8"]            = "pad8",
    ["Pad9"]            = "pad9",
    ["F1"]              = "f1",
    ["F2"]              = "f2",
    ["F3"]              = "f3",
    ["F4"]              = "f4",
    ["F5"]              = "f5",
    ["F6"]              = "f6",
    ["F7"]              = "f7",
    ["F8"]              = "f8",
    ["F9"]              = "f9",
    ["F10"]             = "f10",
    ["F11"]             = "f11",
    ["F12"]             = "f12",
    ["F13"]             = "f13",
    ["F14"]             = "f14",
    ["F15"]             = "f15",
    ["F16"]             = "f16",
    ["F17"]             = "f17",
    ["F18"]             = "f18",
    ["F19"]             = "f19",
    ["F20"]             = "f20",
    ["F21"]             = "f21",
    ["F22"]             = "f22",
    ["F23"]             = "f23",
    ["F24"]             = "f24",
    ["HELP"]            = "help",
    ["HOME"]            = "home",
    ["PageUP"]          = "pageup",
    ["FwdDel"]          = "forwarddelete",
    ["END"]             = "end",
    ["PageDOWN"]        = "pagedown",
    ["CapsLock"]        = "capslock",

    --------------------------------------------------------------------------------
    -- I'm not sure if these have a proper translation on a Mac?
    --------------------------------------------------------------------------------
    ["{"]               = "{",
    ["|"]               = "|",
    ["}"]               = "}",
    ["~"]               = "~",
    ["Umlaut_A"]        = "",
    ["Ring_A"]          = "",
    ["Cedilla_C"]       = "",
    ["Acute_E"]         = "",
    ["Tilde_N"]         = "",
    ["Umlaut_O"]        = "",
    ["Umlaut_U"]        = "",
    ["Acute_a"]         = "",
    ["Grave_a"]         = "",
    ["Circumflex_a"]    = "",
    ["Umlaut_a"]        = "",
    ["Tilde_a"]         = "",
    ["Ring_a"]          = "",
    ["Cedilla_c"]       = "",
    ["Acute_e"]         = "",
    ["Grave_e"]         = "",
    ["Circumflex_e"]    = "",
    ["Umlaut_e"]        = "",
    ["Acute_i"]         = "",
    ["Grave_i"]         = "",
    ["Circumflex_i"]    = "",
    ["Umlaut_i"]        = "",
    ["Tilde_n"]         = "",
    ["Acute_o"]         = "",
    ["Grave_o"]         = "",
    ["Circumflex_o"]    = "",
    ["Umlaut_o"]        = "",
    ["Tilde_o"]         = "",
    ["Acute_u"]         = "",
    ["Grave_u"]         = "",
    ["Circumflex_u"]    = "",
    ["Umlaut_u"]        = "",
    ["Section"]         = "",
    ["German_dbl_s"]    = "",
    ["Acute"]           = "",
    ["Yen"]             = "",
    ["Grave_A"]         = "",
    ["Tilde_A"]         = "",
    ["Tilde_O"]         = "",
    ["Umlaut_y"]        = "",
    ["Umlaut_Y"]        = "",
    ["Circumflex_A"]    = "",
    ["Circumflex_E"]    = "",
    ["Acute_A"]         = "",
    ["Umlaut_E"]        = "",
    ["Grave_E"]         = "",
    ["Acute_I"]         = "",
    ["Circumflex_I"]    = "",
    ["Umlaut_I"]        = "",
    ["Grave_I"]         = "",
    ["Acute_O"]         = "",
    ["Circumflex_O"]    = "",
    ["Grave_O"]         = "",
    ["Acute_U"]         = "",
    ["Circumflex_U"]    = "",
    ["Grave_U"]         = "",
    ["^"]               = "^",
    ["_"]               = "_",
    [">"]               = ".",
    ["?"]               = "?",
    ["@"]               = "@",
    ["#"]               = "#",
    ["$"]               = "$",
    ["%"]               = "%",
    ["&"]               = "&",
    ["LParen"]          = "",
    ["RParen"]          = "",
    ["*"]               = "*",
    ["Plus"]            = "+",

    --------------------------------------------------------------------------------
    -- I'm pretty sure these are PC only?
    --------------------------------------------------------------------------------
    ["NumLock"]         = "",
    ["Insert"]          = "",
    ["Pause"]           = "",
    ["PadInsert"]       = "",
    ["PadDelete"]       = "",
    ["PadHome"]         = "",
    ["PadEnd"]          = "",
    ["PadPageUp"]       = "",
    ["PadPageDown"]     = "",
    ["Backslash"]       = "",
    ["Enter"]           = "",
    ["Backspace"]       = "",
}

--- cp.adobe.aftereffects.shortcuts.modifiers -> table
--- Constant
--- Table containing modifier translations.
mod.modifiers = {
    ["Option"] = "alt",
    ["Shift"] = "shift",
    ["Cmd"] = "cmd",
    ["macControl"] = "ctrl",
}

return mod